image: node:10.16.3
  
pipelines:
  branches: 
    master:
      - step: 
          name: Build
          script:
            - npm i --production
          artifacts:
            - node_modules/**
      - step:
          name: Deploy
          script:
            - npm i serverless -g
            - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - serverless deploy