image: node:10.16.3
  
pipelines:
  branches: 
    master:
      - step:
          name: Test and build
          script:
            - npm i
            - npm run test
            - npm run build
            - rm -rf node_modules
            - npm i --production
          artifacts:
            - dist/**
            - node_modules/**

      - step:
          name: Deploy to staging
          script:
            - npm i serverless -g
            - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - serverless create_domain --stage dev
            - serverless deploy --stage dev

      - step:
          name: Deploy to production
          trigger: manual
          script:
            - npm i serverless -g
            - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - serverless create_domain --stage prod
            - serverless deploy --stage prod