service: api-gateway

provider:
  name: aws
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    JWT_SIGNING_KEY: ${env:JWT_SIGNING_KEY}
  
custom:
  apiGatewayName: ApiGateway-${self:provider.stage}
  authorizerName: ClientAuthorizer-${self:provider.stage}
  
functions:
  clientAuthorizer:
    handler: handler.clientAuthorizer
    cors: true

resources:
  Resources: 
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties: 
        Name: ${self:custom.apiGatewayName}
        Tags:
          -
            Key: Environment
            Value: ${self:provider.stage}
    
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerUri:
          Fn::Join:
            - ''
            -
              - 'arn:aws:apigateway:'
              - Ref: "AWS::Region"
              - ':lambda:path/2015-03-31/functions/'
              - Fn::GetAtt: "ClientAuthorizerLambdaFunction.Arn"
              - "/invocations"
        IdentitySource: method.request.header.Authorization
        IdentityValidationExpression: "Bearer .+"
        Name: ${self:custom.authorizerName}
        RestApiId: { Ref: ApiGateway }
        Type: TOKEN
            
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: ApiGateway 
      Export:
        Name: ${self:custom.apiGatewayName}-restApiId 
       
    apiGatewayRestApiRootResourceId: 
      Value:
        Fn::GetAtt:
          - ApiGateway 
          - RootResourceId 
      Export:
        Name: ${self:custom.apiGatewayName}-rootResourceId

    apiGatewayRestApiAuthorizer:
      Value:
        Ref: ApiGatewayAuthorizer
      Export:
        Name: ${self:custom.apiGatewayName}-authorizer
