service: api-gateway

provider:
  name: aws
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  
custom:
  apiGatewayName: ApiGateway-${self:provider.stage}
  
resources:
  Resources: 
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties: 
        Name: ${self:custom.apiGatewayName}
        
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: ApiGateway 
      Export: 
        Name: ${self:custom.apiGatewayName}-restApiId 
       
    apiGatewayRestApiRootResourceId: 
      Value:
        Fn::GetAtt: 
          - ApiGateway 
          - RootResourceId 
      Export:
        Name: ${self:custom.apiGatewayName}-rootResourceId
