service: api-gateway

provider:
  name: aws
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  
custom:
  exportName: MicroserviceApiGateway-${self:provider.stage}
  
resources:
  Resources: 
    MicroserviceApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties: 
        Name: ${self:custom.exportName}
        
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: MicroserviceApiGateway 
      Export: 
        Name: MicroserviceApiGateway-restApiId 
       
    apiGatewayRestApiRootResourceId: 
      Value:
        Fn::GetAtt: 
          - MicroserviceApiGateway 
          - RootResourceId 
      Export:
        Name: MicroserviceApiGateway-rootResourceId
