service: api-gateway

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  usagePlan:
    throttle:
      burstLimit: 5
      rateLimit: 1
  
resources:
  Resources: 
    MicroserviceApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties: 
        Name: MicroserviceApiGateway
        
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: MicroserviceApiGateway 
      Export: 
        Name: MicroserviceApiGateway-restApiId 
       
    apiGatewayRestApiRootResourceId: 
      Value:
        Fn::GetAtt: 
          - MicroserviceApiGateway 
          - RootResourceId 
      Export:
        Name: MicroserviceApiGateway-rootResourceId
