# API gateway authorizer
# - Our reusable authorizer which we will attach to our API gateway. We will reference the API gateway using the key/name from the "ApiGateway" resource above.
# - The lambda is reference by key/name under functions. For example "clientAuthorizer" becomes "ClientAuthorizerLambdaFunction.Arn".
resources:
  Resources:
    ApiKeyAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerUri:
          Fn::Join:
            - ''
            -
              - 'arn:aws:apigateway:'
              - Ref: "AWS::Region"
              - ':lambda:path/2015-03-31/functions/'
              - Fn::GetAtt: "ApiKeyAuthorizerLambdaFunction.Arn"
              - "/invocations"
        IdentitySource: method.request.header.Authorization
        IdentityValidationExpression: "Bearer .+"
        Name: ${self:custom.apiKeyAuthorizerName}
        AuthorizerResultTtlInSeconds: '0'
        RestApiId: { Ref: ApiGatewayRestApi }
        Type: TOKEN

    ApiKeyAuthorizerPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::GetAtt: ApiKeyAuthorizerLambdaFunction.Arn
        Principal: "apigateway.amazonaws.com"
        SourceArn:
          Fn::Join:
            - ""
            -
              - "arn:aws:execute-api:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":"
              - Ref: ApiGatewayRestApi
              - "/authorizers/"
              - Ref: ApiKeyAuthorizer

  Outputs:
    apiKeyAuthorizer:
      Value:
        Ref: ApiKeyAuthorizer
      Export:
        Name: ${self:custom.apiGatewayName}-api-key-authorizer