# Table: InternalApiKeysTable
# ===========================
# - Stores api keys
resources:
  Resources:
    InternalApiKeysTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: internal_api_keys-${self:provider.stage}
        AttributeDefinitions:
          -
            AttributeName: identifier_key
            AttributeType: S
        KeySchema:
          -
            AttributeName: identifier_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
