# Table: InternalServicePoliciesTable
# ===============================
# - Stores service policies
resources:
  Resources:
    InternalServicePoliciesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: internal_service_policies-${self:provider.stage}
        AttributeDefinitions:
          -
            AttributeName: service_name_version
            AttributeType: S
        KeySchema:
          -
            AttributeName: service_name_version
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5