name: Microservice - API Gateway
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Use Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Serverless deploy
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          npm i serverless -g
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          serverless deploy
        env:
          JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
